[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_manager = "7NYupbzS2cL96Yyx6bAvxJeee75iNFuPaDtGuNw7jTRs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nseguias/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
