[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_manager = "CKTYiehaWakXn89NpFsuf1dC5m3QBthXQLNjUkC7ng8z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nseguias/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Added this troubleshooting
[build]
solana_version = "2.1.14"
